language: python

stages:
  - test
  - name: deploy
    if: type != pull_request

jobs:
  include:
    - python: 3.6
    - python: 3.7

    - stage: deploy
      python: 3.7
      script: "python -m statik.cmdline --deploy=netlify -p examples/blog -v"

install:
  - "pip install -r requirements.txt"
  - "pip freeze"
script:
  - "python -m unittest discover"
  - pip install .
