language: python

stages:
  - test
  - name: deploy
    if: type != pull_request

jobs:
  include:
    - python: 3.6
      python: 3.7

    - stage: deploy
      python: 3.6
      script: "python -m statik.cmdline --upload=netlify --netlify-site-id=$NETLIFY_SITE_ID -p examples/blog"

install:
  - "pip install -r requirements.txt"
script:
  - "python -m unittest discover"
  - pip install .
